env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:prettier/recommended
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - '@typescript-eslint'
  - react
  - import
  - only-warn

settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
      paths: ['src']
      moduleDirectory:
        - 'node_modules'
        - 'src/'

rules:
  react/prop-types: 0
  react/no-unescaped-entities: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: 'react'
          group: 'external'
          position: 'before'
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

globals:
  process: true